admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin/

rest:
    resource: "@RestBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
